### ISSUE TITLE
关联查询抛空异常

### ISSUE THREAD

**Issue by MuYiSend** [elvinzeng/nwf#22]
![image](https://cloud.githubusercontent.com/assets/25809202/25061713/f735325c-21ee-11e7-96b4-96ea11b758e5.png)
抛出以上错误   

sql语句如下  
![image](https://cloud.githubusercontent.com/assets/25809202/25061717/22120356-21ef-11e7-8eb5-a0b7498b41e1.png)

映射如下 
![image](https://cloud.githubusercontent.com/assets/25809202/25061719/2ee116e4-21ef-11e7-967b-6ddcb53501e9.png)

**Comment by MuYiSend** [comment]
移除关联以后可以正常查询
![image](https://cloud.githubusercontent.com/assets/25809202/25061791/7eebf086-21f0-11e7-9031-7ad2a9b2bab5.png)

**Comment by elvinzeng** [comment]
检查Mapper继承的父类有没有问题
