### ISSUE TITLE
关联查询异常

### ISSUE THREAD

**Issue by MuYiSend** [elvinzeng/nwf#5]
**错误信息：**
error: function [get], file [www/controller/DemoController.lua], line number [38].

[string "script/ide/STL/UnorderedArraySet.lua"]:115: table index is nil

stack traceback:
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:284: in function '__newindex'
	[string "script/ide/STL/UnorderedArraySet.lua"]:115: in function 'add'
	[string "npl_packages/nwf/npl_mod/nwf/db/dbTemplate.lua"]:84: in function 'getListFromCursor'
	[string "npl_packages/nwf/npl_mod/nwf/db/dbTemplate.lua"]:270: in function 'queryFirst'
	[string "www/controller/DemoController.lua"]:67: in function 'action'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:261: in function <[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:242>
	[C]: in function 'xpcall'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:242: in function 'process'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:305: in function <[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:304>
	[C]: in function 'xpcall'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:304: in function 'doNext'
	[string "npl_packages/nwf/npl_mod/nwf/session.lua"]:157: in function <[string "npl_packages/nwf/npl_mod/nwf/session.lua"]:149>
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:300: in function <[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:299>
	[C]: in function 'xpcall'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:299: in function 'doFilter'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:302: in function 'doNext'
	[string "npl_packages/nwf/npl_mod/nwf/loader.lua"]:49: in function <[string "npl_packages/nwf/npl_mod/nwf/loader.lua"]:40>
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:300: in function <[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:299>
	[C]: in function 'xpcall'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:299: in function 'doFilter'
	[string "npl_packages/nwf/npl_mod/nwf/dispatcher.lua"]:340: in function 'handle'
	[string "www/router.lua"]:9: in function <[string "www/router.lua"]:8>

**测试代码：**
	local sql = "SELECT c.cart_id AS cid , u.user_name AS uname FROM  tb_cart c LEFT JOIN tb_user u ON c.user_id = u.user_id WHERE c.cart_id='7f293e5d-a1bf-403c-c091-49d144021be9'";

	local data,err = dbTemplate:queryFirst(sql, {"tb_cart","tb_user"});
**model内容：**

local user = commonlib.gettable("entity.user");  
user.tbName = "tb_user";  
user.fields = {
	user_id = {notNil = true,isPrimaryKey = true},
	user_name = {notNil = false},
	password = {notNil = false},
	eidt_time = {notNil = false},
	create_time = {notNil = false},
	is_deleted = {notNil = false}
}

local cart = commonlib.gettable("entity.cart");  
cart.tbName = "tb_cart";  
cart.fields = {
	cart_id = {notNil = true,isPrimaryKey = true},
	user_id = {notNil = true},
	product_price = {notNil = true},
	eidt_time = {notNil = false},
	create_time = {notNil = false},
	is_deleted = {notNil = false}
}

**Comment by elvinzeng** [comment]
参考[最新的文档](https://github.com/elvinzeng/nwf/blob/master/doc/zh-hans/database-access.md)
